### ISSUE TITLE
Nice Project

### ISSUE THREAD

**Issue by jcbriones** [mattpolzin/VaporOpenAPIExample#2]
Hey nice project matt. I was looking for something like this and yours is just what I need. I've been looking at the example though. Do you have any sample for query parameters? I see path which works out of the box. I'm guessing query parameter is something extra? Thanks in advance.

**Comment by mattpolzin** [comment]
Sure; there’s a “string” query parameter in the example in this repository here: https://github.com/mattpolzin/VaporOpenAPIExample/blob/main/Sources/App/Controllers/HelloWorldController.swift#L53

In another project of mine, I’ve specified a “comma separated value” query parameter here: https://github.com/mattpolzin/jsonapi-openapi-test-server/blob/main/Sources/App/Controllers/APITestController.swift#L267

**Comment by jcbriones** [comment]
I see it. Thank you. This is helpful! Although, I don't use the context stuff that's why I didn't notice it was there. I'm actually curious why design it using a RouteContext? I like the dot notation for the description, summary, tags that works just extending Vapor framework. But then others like `parameterType(_:)` requires the route to be modified. Can those be like dot notations as well without modifying the PathComponent to be TypePathComponent?

**Comment by mattpolzin** [comment]
The route context is there to reduce overall effort if you are interested in a certain kind of integration. That is, if you do implement route contexts, they give you OpenAPI documentation at the same time as offering up an interface for retrieving properties of a request in your controller code -- you write about a parameter once in the route context, then you generate docs _and_ use automatically available accessors to write your controllers. There's a sort of guarantee that comes with that way of doing things that your documentation and actual controller code use the same properties by the same name with the same types.

The dot-notation description, summary, etc. is done that way because those are things that don't have any runtime representation generally so I don't expose them as conveniences on the controller side and there's no better place to set them than right on the code that hooks the route up.

Here's what I mean when I say you get accessors in your controller from the same code as you get documentation: https://github.com/mattpolzin/VaporOpenAPIExample/blob/main/Sources/App/Controllers/HelloWorldController.swift#L13. `req.query.language` _is_ the runtime value for the property defined as `language` in the route context  here: https://github.com/mattpolzin/VaporOpenAPIExample/blob/main/Sources/App/Controllers/HelloWorldController.swift#L53.

It's not for everyone, but that's the reasoning behind the design.

**Comment by jcbriones** [comment]
Thank you for the explanation. I get it now. Thanks. I will have to do some refactoring on my architecture to support this. Thank you
